### ISSUE TITLE
cdens filtering by material

### ISSUE THREAD

**Issue by AlvaroCubi** [travleev/numjuggler#5]
Hello and great job with the  recent changes.
I have noticed that the cdens function may apply directly a density value to the cell instead of a factor when filtering by material instead of filtering by cells. Is there a reason for that?

**Comment by travleev** [comment]
Original intention was to treat all values in the map file as multiplying coefficients.
I put modifications (there were other bugs in cdens mode) into the issue5 branch. It contains also several test cases for travis. Note that the added test cases are passed for Python 2.7 but fail for python 3.7

**Comment by travleev** [comment]
Tests failed for Python3 because `str(1.1*0.1)` returns `0.11` in Python2 and `0.110000..01` in Python3. In order to provide the same behaviour in Python2 and Python3, the new density value is formatted with `string.format` . The formatting string can be specified after the multiplication coefficient, see docs for cdens.
